spring:
  application:
    name: auth-service
    domain: localhost
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
  jwt:
    secret: ${JWT_SECRET}
    expiration:
      access-minutes: 15
      refresh-days: 30

server:
  servlet:
    context-path: /auth

